hyostagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:post_id>/edit/', views.edit, name='edit'),
    path('<int:post_id>/update/', views.update, name='update'),
    path('<int:post_id>/delete/', views.delete, name='delete'),
    path('<int:post_id>/like/', views.like, name='like'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Post(models.Model):

    # author = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    body = models.TextField()
    image = models.ImageField(upload_to='post', null=True)
    created_at = models.DateTimeField()
    liked_users = models.ManyToManyField(User, related_name='liked_posts')

    def __str__(self):
        if self.user:
            return f'{self.user.get_username()}: {self.body}'

        return f'{self.body}'

posts/views.py
from django.shortcuts import render, redirect
from .models import Post
from django.utils import timezone
from django.contrib.auth.decorators import login_required


# Create your views here.


def index(request):
    posts = Post.objects.all()

    context = {'posts': posts}

    return render(request, 'posts/index.html', context)


def detail(request, post_id):
    post = Post.objects.get(id=post_id)

    context = {'post': post}

    return render(request, 'posts/detail.html', context)


@login_required
def new(request):

    return render(request, 'posts/new.html')


@login_required
def create(request):

    user = request.user
    body = request.POST['body']

    image = None
    if 'image' in request.FILES:
        image = request.FILES['image']

    post = Post(user=user, body=body, image=image, created_at=timezone.now())
    post.save()

    return redirect('posts:detail', post_id=post.id)


@login_required
def edit(request, post_id):
    try:
        post = Post.objects.get(id=post_id, user=request.user)
    except Post.DoesNotExist:
        return redirect('posts:index')

    context = {'post': post}
    return render(request, 'posts/edit.html', context)


@login_required
def update(request, post_id):
    try:
        post = Post.objects.get(id=post_id, user=request.user)
    except Post.DoesNotExist:
        return redirect('posts:index')

    post.body = request.POST['body']

    if 'image' in request.FILES:
        post.image = request.FILES['image']

    post.save()

    return redirect('posts:detail', post_id=post.id)


@login_required
def delete(request, post_id):
    try:
        post = Post.objects.get(id=post_id, user=request.user)
    except Post.DoesNotExist:
        return redirect('posts:index')

    post.delete()

    return redirect('posts:index')


@login_required
def like(request, post_id):

    if request.method == 'POST':
        try:
            post = Post.objects.get(id=post_id)

            if request.user in post.liked_users.all():
                post.liked_users.remove(request.user)
            else:
                post.liked_users.add(request.user)

            return redirect('posts:detail', post_id=post.id)

        except Post.DoesNotExist:
            pass

    return redirect('posts:index')

posts/templates/posts/detail.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Post Detail</h1>

    {% if post.image %}
      <div>
        <img src="{{ post.image.url }}" alt="Post Image" />
      </div>
    {% endif %}

    <div class="form-group">
      <label for="author">작성자</label>
      <input readonly class="form-control-plaintext" type="text" name="author" value="{{ post.user.get_username }}" />
    </div>

    <div class="form-group">
      <label for="body">본문</label>
      <textarea readonly class="form-control-plaintext" id="body" cols="40" rows="10" name="body">{{ post.body }}</textarea>
    </div>

    <div>{{ post.created_at }}</div>

    <div>좋아요 수: {{ post.liked_users.count }}</div>

    {% if user.is_authenticated %}
      <form action="{% url 'posts:like' post.id %}" method="POST">
        {% csrf_token %}

        {% if user in post.liked_users.all %}
          <button type="submit" class="btn btn-primary">LIKE</button>
        {% else %}
          <button type="submit" class="btn btn-secondary">LIKE</button>
        {% endif %}
      </form>
    {% endif %}

    <a href="{% url 'posts:index' %}">목록</a>
    {% if user == post.user %}
      <a href="{% url 'posts:edit' post.id %}">수정하기</a>
      <a href="{% url 'posts:delete' post.id %}">삭제하기</a>
    {% endif %}
  </div>
{% endblock %}

posts/templates/posts/edit.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Edit Post</h1>

    {% if post.image %}
      <div>
        <img src="{{ post.image.url }}" alt="Post Image" />
      </div>
    {% endif %}    

    <form action="{% url 'posts:update' post.id %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="body">본문</label>
        <textarea class="form-control" id="body" cols="40" rows="10" name="body">{{ post.body }}</textarea>
      </div>

      <div class="form-group">
        <label for="image">이미지</label>
        <input type="file" class="form-control-file" id="image" name="image" />
      </div>

      <button type="submit" class="btn btn-primary">수정하기</button>
    </form>

    <a href="{% url 'posts:index' %}">목록</a>    
  </div>
{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Posts</h1>

    {% if posts %}
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>작성자</th>
          <th>본문</th>
          <th>게시일</th>
          <th>상세</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <th>{{ post.id }}</th>
          <td>{{ post.user.get_username }}</td>
          <td>{{ post.body }}</td>
          <td>{{ post.created_at }}</td>
          <td><a href="{% url 'posts:detail' post.id %}">보기</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
      <p>No Posts.</p>
    {% endif %}

    <a href="{% url 'posts:new' %}">글쓰기</a>
  </div>
{% endblock %}

posts/templates/posts/new.html
{% extends "base.html" %}

{% load static %}

{% block style %}
  <link rel="stylesheet" href="{% static 'posts/style.css'%}" />
{% endblock %}

{% block content %}
  <div class="container">
    <h1>New Post</h1>

    <form action="{% url 'posts:create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="form-group">
        <label for="body">본문</label>
        <textarea class="form-control" id="body" cols="40" rows="10" name="body"></textarea>
      </div>

      <div class="form-group">
        <label for="image">이미지</label>
        <input type="file" class="form-control-file" id="image" name="image" />
      </div>

      <button type="submit" class="btn btn-primary">작성하기</button>
    </form>

    <a href="{% url 'posts:index' %}">목록</a>    
  </div>
{% endblock %}